[package]
name = "crui"
version = "0.1.0"
authors = ["Rodrigo Batista de Moraes <rodrigobatsmoraes@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["./crui-derive"]

[features]

# serde = ["serde", "ron"]
simple_shaping = []

[dependencies]

texture-cache = { path = "../texture-cache" }
ab_glyph = "0.2"
harfbuzz_rs = "2"
unicode-linebreak = "0.1"
unicode-segmentation = "1"
winit = "0.26"
bitflags = "1"
copypasta = "0.7"
serde = { version = "1", features = ["derive"] }
crui-derive = { path = "./crui-derive" }
keyed_priority_queue = "0.3"
log = "0.4"


[dev-dependencies]

image = { version = "0.23", default-features = false, features=["png"] }
rand = { version = "0.8", features = ["small_rng"] }
sprite-render = { path = "../sprite-render-rs", features=["opengl"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
ron = "0.6"
env_logger = "0.9.0"
