[package]
name = "ui_engine"
version = "0.1.0"
authors = ["Rodrigo Batista de Moraes <rodrigobatsmoraes@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

sprite-render = { path = "../sprite-render-rs", features=["opengl"] }
glyph_brush_layout = "0.2"
glyph_brush_draw_cache = "0.1"
winit = "0.22"
bitflags = "1"

[dev-dependencies]

image = { version = "0.23", default-features = false, features=["png"] }