[package]
name = "ui_engine"
version = "0.1.0"
authors = ["Rodrigo Batista de Moraes <rodrigobatsmoraes@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

glyph_brush_draw_cache = "0.1"
ab_glyph = "0.2"
xi-unicode = "0.3"
winit = "0.24"
bitflags = "1"
copypasta = "0.7"

[patch.crates-io]
winit = { path = "../winit" }

[dev-dependencies]

image = { version = "0.23", default-features = false, features=["png"] }
sprite-render = { path = "../sprite-render-rs", features=["opengl"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = { version = "0.8", features = ["small_rng"] }